var globalMovieData;

$(function () {

    //console.log("jquery is loaded");
    startUp();
    loadMovies();

})

function startUp() {

    $(".container").on('click', ".viewMovie", function () {
        var movieId = $(this).data("id");
        bookMovie(movieId)

    })

    $(".container").on('change', "#chooseDay", function () {

        var id = $(this).data("movieid");
        var day = $(this).val();

        console.log(`You chose day ${day} for movie id ${id}`);
        console.log(globalMovieData[id].runningTimes);

        switch (day) {
            case "mon": times = globalMovieData[id].runningTimes.mon; break;
            case "tue": times = globalMovieData[id].runningTimes.tue; break;
            case "wed": times = globalMovieData[id].runningTimes.wed; break;
            case "thu": times = globalMovieData[id].runningTimes.thu; break;
            case "fri": times = globalMovieData[id].runningTimes.fri; break;
            case "sat": times = globalMovieData[id].runningTimes.sat; break;
            case "sun": times = globalMovieData[id].runningTimes.sun; break;
            default: times = [];

        }
        console.log(times);

        if (times.length == 0) {

            $('#chooseTime').empty().prop('disabled', true);
            return;

        }

       //empty select
       //append the array of options generated by map and joined 

        $('#chooseTime').empty().append( times.map( t => {

            return `<option value="${t}">${t}</option>`;
        
        }).join(" ") ).prop('disabled', false);

    

    })




}

function loadMovies() {

    var url = 'http://college-movies.herokuapp.com/';

    $.getJSON(url, function (jsonData) {

        globalMovieData = jsonData;

        console.log(jsonData);

        var templateData = []

        for (var i = 0; i < jsonData.length; i++) {

            templateData.push(getMovieTemplate(i, jsonData[i]));
        }



        $('#movieListing').append(templateData.join(" "));

    })


}


function getMovieTemplate(id, movieItem) {

    return `<div class="card" style="width: 18rem;">
               
    <div class="card-body">
      <h5 class="card-title">${movieItem.title} <span class="badge badge-secondary">${movieItem.genre}</span></h5>
      ${getCastTemplate(movieItem.cast.split(","))}
      <p class="card-text"></p>
      <button class="btn btn-primary viewMovie" data-id="${id}">View Movie</button> 
     
    </div>
  </div>`;

}


function getMovieBookingTemplate(id, movieItem) {

    return `<div class="card" style="width: 18rem;">
               
    <div class="card-body">
      <h5 class="card-title">${movieItem.title}</h5>
      <p class="card-text"></p>
        <div class="row">
                <div class="col-md-6">Mon</div>
                <div class="col-md-6">${getMovieTemplateTimes(movieItem.runningTimes.mon)}</div>
        </div>
        <div class="row">
        <div class="col-md-6">Tue</div>
        <div class="col-md-6">${getMovieTemplateTimes(movieItem.runningTimes.tue)}</div>
</div>
<div class="row">
<div class="col-md-6">Wed</div>
<div class="col-md-6">${getMovieTemplateTimes(movieItem.runningTimes.wed)}</div>
</div>


<div class="row">
<div class="col-md-6">
<select id="chooseDay" data-movieId="${id}">
<option value="">Select A Day</option>
<option value="mon">Monday</option>
<option value="tue">Tuesday</option>
<option value="wed">Wednesday</option>
<option value="thu">Thursday</option>
<option value="fri">Friday</option>
<option value="sat">Saturday</option>
<option value="sun">Sunday</option>
</select>
</div>
<div class="col-md-6"><select id="chooseTime" disabled><option>Choose Day</option></select></div>
</div>


      <button class="btn btn-primary bookMovie" data-id="${id}">Book Movie</button> 
    
    </div>
  </div>`;

}


function getCastTemplate(cast) {

    var html = [];
    html.push("<ul>");
    for (var i = 0; i < cast.length; i++) {

        html.push(getCastTemplateItem(cast[i]));
    }
    html.push("</ul>");

    return html.join(" ");
}


function getCastTemplateItem(item) {

    return `<li>${item}</li>`;

}


function bookMovie(id) {

    console.log(`You want to book ${id}`)

    console.log(globalMovieData[id]);

    $('#movieDetail').html(getMovieBookingTemplate(id, globalMovieData[id]));

}


function getMovieTemplateTimes(day) {


    var days = day.map(x => {

        return `<option value='${x}'>${x}</option>`;

    });


    return `<select>${days.join(" ")}</select>`


}
